apiVersion: v1
kind: ConfigMap
metadata:
  name: nsqauthj-configuration
data:
  config.yaml: |
    health:
      delayedShutdownHandlerEnabled: true
      shutdownWaitPeriod: 15s
    heartbeater:
      type: Heartbeater
      url: http://heartbeater/hb/
    metrics:
      frequency: 30 seconds
      reporters:
        - type: graphite
          durationUnit: seconds
          rateUnit: minutes
          prefix: infrastructure.dbre.nsqauth
          host: carbon-useast1.int.sproutsocial.com
          port: 2003
    logging:
      level: INFO
      loggers:
        com.sproutsocial.nsqauthj: INFO
        NsqPermissionAudit:
          level: ALL
          additive: false
          appenders:
            - type: console
              layout:
                type: json
      appenders:
        - type: console
          threshold: ALL
          layout:
            type: json
    server:
      applicationConnectors:
        - type: http
          port: 4181
          useForwardedHeaders: true
        - type: http
          port: 8080
          useForwardedHeaders: true
      requestLog:
        appenders:
          - type: console
            timeZone: UTC
            threshold: ALL
            layout:
              type: access-secret-masking-json
              patterns:
                - "secret=[^&]*"
      shutdownGracePeriod: 10s
    tokenValidation:
      serviceTokenPath: secret/services/nsq/service-tokens/
      userTokenPath: secret/services/nsq/user-tokens/
      tokenTTL: 3600
      failOpen: false
    vault:
      type: jwt
      authPath: k8s-
      role: nsqauthd
      addr: https://vault.int.sproutsocial.com
      engineVersion: 2
      renewable: true
      renewInterval: 3600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsqauthj
  labels:
    app: nsqauthj
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nsqauthj
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nsqauthj
        json-logging: structured
        version: ${IMAGE_TAG}
    spec:
      serviceAccountName: vault-auth
      volumes:
        - name: nsqauthj-configuration
          configMap:
            name: nsqauthj-configuration
      containers:
        - name: nsqauthj
          image: 412335208158.dkr.ecr.us-east-1.amazonaws.com/nsqauthj:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          command: [ 'java' ]
          args: [
            '-Xmx512m',
            '-Dcom.sun.management.jmxremote',
            '-Dcom.sun.management.jmxremote.ssl=false',
            '-Dcom.sun.management.jmxremote.authenticate=false',
            '-Dcom.sun.management.jmxremote.port=22978',
            '-Dcom.sun.management.jmxremote.rmi.port=22978',
            '-Dcommons.config=yaml:/srv/nsqauthj/configs/config.yaml',
            '-jar',
            'nsqauthj.jar'
          ]
          ports:
            - containerPort: 4181
              name: nsqauthd
            - containerPort: 22978
              name: jmx
          livenessProbe:
            httpGet:
              path: /health-check?type=alive
              port: nsqauthd
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health-check?type=ready
              port: nsqauthd
            periodSeconds: 5
            failureThreshold: 2
            initialDelaySeconds: 45
          startupProbe:
            httpGet:
              path: /health-check?type=ready
              port: nsqauthd
            failureThreshold: 12
            periodSeconds: 5
          volumeMounts:
            - name: nsqauthj-configuration
              mountPath: '/srv/nsqauthj/configs/'
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: nsqauthj
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  selector:
    app: nsqauthj
  ports:
    - name: prod
      port: 4181
      targetPort: nsqauthd
  type: LoadBalancer